#simple datatypes
#compound data types
print(" ")
print("transaction1=10.20")
print("transaction2=31.32")
print("transaction3=5")
print("print(transaction1+transaction2+transaction3)")
print("but these are the of the same type")
print(" ")
print("python therefore has a list")
print("transactions=[10.20,31.32,5]")
transactions=[10.20,31.32,5]
print(f"print(sum(transactions))",sum(transactions))
print(" ")
print("transactions.append(7.82)")
transactions.append(7.82)
print("transactions=[10.20,31.32,5,7.82]")
print(transactions)
print("append kan maar ook transactions.pop() dat is de laatste waarde van de lijst die verdwijnt")
transactions.pop()
print(transactions)
print(" ")
print("indexing als je een waarde uit de lijst wil hebben bijvoorbeeld transactions[1]")
print("de laatste transactions[-1] uit de lijst door transactions[-1]")
print(f"de tweede transactions[1] uit de lijst is ",transactions[1])
print(f"de laatste transactions[-1] uit de lijst is ",transactions[-1])
print(" ")
print("transactions.insert(1,40.8) wil put 40.8 before 31.32 ")
print(f"the second value 10.20  31.32  5  is {transactions[1]}")
print(" ")
print("telefoonboek phonebook={[]}")
phonebook={"alice":"555-1234","bob":"555-1324","lodewijk":"555-6663"}
print("alice 555-1234  bob 555-1324   lodewijk 555-6663")
print("the number of bob is phonebook['bob']")
print(f"het nummer van bob is {phonebook['bob']}")
print(" ")

